name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '00 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          DEBUG_LOGGING: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_LINES_OF_CODE: "FALSE"
